# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
issues:
  max-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - internal/aws
    - internal/diagnostics
    - internal/errs
    - internal/framework
    - internal/maps
    - internal/planmodifiers

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - copyloopvar
    - forcetypeassert
    - godot
    - gofmt
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - tenv
    - unconvert
    - unparam
    - unused
    - govet
